<script lang="ts">
	import ComparisonObject from '../component/comparisonObject.svelte';
	import ResultsComponent from '../component/results.svelte';
	import type { Trip } from '$lib/interface/Trip';
	import { onMount } from 'svelte';
	import { getAllAirports } from '$lib/stores/airportStore';
	import { getAllMakes } from '$lib/stores/vehicleStore';
	import { formValidate } from '$lib/helper/formValidator';
	import Error from '../component/utilities/error.svelte';

	let compared: Boolean = false;
	let unique = {};
	let errors: string[] = [];
	let expanded: boolean = false;
	let clamp: string;

	$: if (expanded === true) {
		clamp = 'line-clamp-none';
	} else {
		clamp = 'line-clamp-3';
	}

	let tripsObj: Trip[] = [
		{
			transport_obj: [{ type: null }],
			carbon_g: null
		},
		{
			transport_obj: [{ type: null }],
			carbon_g: null
		}
	];

	const hideError = (event: any) => {
		const errorText = event.detail.object;
		const filteredErrors = errors.filter((error) => {
			if (error !== errorText) {
				return error;
			}
		});
		errors = filteredErrors;
	};

	const expand = () => {
		expanded = !expanded;
	};

	const compare = () => {
		let success: boolean = true;
		let error: string[] = [];
		console.log(tripsObj);
		tripsObj.forEach((trip) => {
			trip.transport_obj.forEach((transport) => {
				const validation = formValidate(transport);
				if (validation === undefined) {
					success = false;
					error.push('One or more transport object(s) is/are empty!');
					return;
				}
				if (validation.success === false) {
					success = false;
					validation.error.errors.forEach((validationError) => {
						error.push(validationError.message);
					});

					return;
				}
			});
		});
		errors = error;
		compared = success;
	};

	const reset = () => {
		unique = {};
		const obj: Trip[] = [
			{
				transport_obj: [{ type: null }],
				carbon_g: null
			},
			{
				transport_obj: [{ type: null }],
				carbon_g: null
			}
		];

		tripsObj = obj;
		compared = false;
	};

	onMount(async () => {
		getAllAirports();
		getAllMakes();
	});
</script>

<article class="bg-cyan-500 p-4">
	<p class="lg:line-clamp-none {clamp} p-1" on:click={expand}>
		This application is designed to measure the carbon efficiency of different travel options. By
		providing data on the carbon footprint of each option, you can make more informed decisions
		about how to travel in a way that minimizes your impact on the environment. Before you get
		started, I want to disclose that this is just a part of my developer portfolio and not an actual
		production version. However, if you find it useful, I encourage you to consider donating to the
		API makers FlightLabs and Carbon Interface, who have provided the underlying technology that
		powers this application. Your support will help them continue to innovate and make their APIs
		available for developers like myself to use in creating useful tools like this one. If you have
		any non-API related questions, comments, or feedback, please feel free to reach out to me on
		LinkedIn or Github. I am always interested in connecting with other developers and learning from
		their experiences. Thank you for taking the time to try out this application and I hope to hear
		from you soon!
	</p>
	Tech stack:
	<ul class="list-disc list-inside">
		<li>Sveltekit</li>
		<li>TailwindCSS</li>
		<li>TRPC</li>
		<li>Zod</li>
		<li>and much more...</li>
	</ul>
	<p class="p-1">You can find more information in the applications Github repository!</p>
	<p class="p-1">
		ps.: The introduction was actually generated by ChatGPT, just to throw in some fancy AI stuff...
	</p>
</article>
{#each errors as error}
	<Error errorText={error} on:hideError={hideError} />
{/each}

{#key unique}
	<main class="flex flex-wrap flex-row justify-evenly">
		<ComparisonObject bind:transportObjects={tripsObj[0].transport_obj} />
		<ComparisonObject bind:transportObjects={tripsObj[1].transport_obj} />
	</main>
{/key}
<section class="flex justify-center">
	<button on:click={() => compare()}>Compare <i class="bi bi-search" /></button>
	<button on:click={() => reset()}>Reset <i class="bi bi-x-circle-fill" /></button>
</section>
{#if compared}
	<ResultsComponent left_carbon="0" right_carbon="0" />
{/if}
